name: Package gradio example with PyInstaller - Windows
on:
  workflow_dispatch:
  push:
    branches: [ main, demo ]
jobs:
  build-win-exe:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install package management
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: pip install -r eval-requirements.txt -r dev-requirements.txt
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build executable
      run: pyinstaller .\examples\demo_gradio.spec
    - uses: actions/upload-artifact@v2
      with:
        name: pdf-to-aas-gradio-demo
        path: dist/demo_gradio.exe
